const equipment = [
    { id: 'tractor-40hp', name: 'Tractor 40 HP', icon: '🚜', providerName: 'Nallapadu Farm Machinery', providerId: 'provider-nfm', location: 'Nallapadu', price: 1800, unit: 'day', availability: 'Available', rating: '4.7/5 (DEMO)', description: 'Utility tractor for land preparation, hauling and routine field work.', dates: 'Available this week', requirements: 'Operator experience and suitable farm access' },
    { id: 'rotavator-pro', name: 'Rotavator Pro', icon: '🌾', providerName: 'Green Field Rentals', providerId: 'provider-gfr', location: 'Guntur', price: 1150, unit: 'day', availability: 'Available', rating: '4.5/5 (DEMO)', description: 'Tilling support for seedbed preparation and soil conditioning.', dates: 'Available from tomorrow', requirements: 'Compatible tractor connection' },
    { id: 'harvester-combine', name: 'Combine Harvester', icon: '🌾', providerName: 'Harvest Route Services', providerId: 'provider-hrs', location: 'Tenali', price: 2600, unit: 'day', availability: 'Limited dates', rating: '4.6/5 (DEMO)', description: 'Harvesting support for larger field operations.', dates: 'Book in advance', requirements: 'Clear field access and crop readiness' },
    { id: 'cultivator', name: 'Cultivator', icon: '🚜', providerName: 'Guntur Agri Tools', providerId: 'provider-gat', location: 'Guntur', price: 900, unit: 'day', availability: 'Available', rating: '4.4/5 (DEMO)', description: 'Cultivation attachment for routine field preparation.', dates: 'Available this week', requirements: 'Compatible tractor connection' },
    { id: 'seed-drill', name: 'Seed Drill', icon: '🌱', providerName: 'SeedSmart Rentals', providerId: 'provider-ssr', location: 'Vijayawada', price: 1250, unit: 'day', availability: 'On request', rating: '4.3/5 (DEMO)', description: 'Seed placement equipment for planned sowing activities.', dates: 'Confirm provider dates', requirements: 'Prepared seedbed and compatible tractor' },
    { id: 'sprayer', name: 'Field Sprayer', icon: '💧', providerName: 'CropCare Equipment', providerId: 'provider-cce', location: 'Guntur', price: 700, unit: 'day', availability: 'Available', rating: '4.2/5 (DEMO)', description: 'Field spraying equipment for planned crop-care activities.', dates: 'Available this week', requirements: 'Follow product label and local safety guidance' },
    { id: 'thresher', name: 'Mobile Thresher', icon: '⚙️', providerName: 'Kisan Utility Services', providerId: 'provider-kus', location: 'Kurnool', price: 2100, unit: 'day', availability: 'Limited dates', rating: '4.5/5 (DEMO)', description: 'Threshing support for post-harvest handling.', dates: 'Book in advance', requirements: 'Dry crop and vehicle access' }
];
export const getEquipment = () => equipment.map((item) => ({ ...item }));
